//go:build vmsvectors

package vectors

import (
	"crypto"
	"crypto/hmac"
	"crypto/sha256"
	"crypto/x509"
	"encoding/base64"
	"strings"
	"time"

	"github.com/vettid/vettid-vault/vms/altchan"
)

// genAppKey builds appkey.json (VAULT-MESSAGING 0.15.0 §11.12,
// ENROLLMENT-CODES.md): the app key and its akid, two signed requests
// (an unlock and a redeem) with their signing strings and headers (ECDSA
// P-256, RFC 6979 nonces), the typed code's rejection sampling, the API's
// MACs, and both QR payloads with api.
func genAppKey() (obj, error) {
	k, err := p256(SeedAppKey)
	if err != nil {
		return nil, err
	}
	der, err := x509.MarshalPKIXPublicKey(&k.PublicKey)
	if err != nil {
		return nil, err
	}
	akid := altchan.AppKeyID(der)
	t0, _ := time.Parse(time.RFC3339, "2026-10-01T12:00:00Z")
	nonce := base64.RawURLEncoding.EncodeToString(rep(NonceApp, 16))
	sign := func(r *altchan.AppRequest) (obj, error) {
		s := r.SigningString()
		h := sha256.Sum256([]byte(s))
		sig, err := k.Sign(nil, h[:], crypto.SHA256) // RFC 6979
		if err != nil {
			return nil, err
		}
		bh := sha256.Sum256(r.Body)
		return obj{{"method", r.Method}, {"path", r.Path}, {"query", r.Query}, {"vault_id", r.VaultID}, {"ts", int(t0.Unix())},
			{"nonce", r.Nonce}, {"body", string(r.Body)}, {"body_sha256_hex", hx(bh[:])}, {"signing_string", s},
			{"sig_b64url", base64.RawURLEncoding.EncodeToString(sig)}, {"header", r.Header(sig)}}, nil
	}
	secret := rep(SeedQRSecret, altchan.QRSecretSize)
	qs := base64.RawURLEncoding.EncodeToString(secret)
	unlockBody := `{"vault_id":"` + ACAppVaultID + `","request_id":"01JB2Z6V9K3M4N5P6Q7R8S9T40","instance_id":"i-test","etk_kid":"0011223344556677","envelope":"AAAA","manifest_sha256":"` + strings.Repeat("ab", 32) + `"}`
	unlock, err := sign(&altchan.AppRequest{Method: "POST", Path: "/api/vault/unlock", VaultID: ACAppVaultID, KID: akid, TS: t0.Unix(),
		Nonce: nonce, Body: []byte(unlockBody)})
	if err != nil {
		return nil, err
	}
	redeemBody := `{"secret":"` + qs + `","app_key":"` + b64(der) + `"}`
	redeem, err := sign(&altchan.AppRequest{Method: "POST", Path: "/api/vault/enroll/redeem", KID: akid, TS: t0.Unix(), Nonce: nonce,
		Body: []byte(redeemBody)})
	if err != nil {
		return nil, err
	}
	enclave, err := sign(&altchan.AppRequest{Method: "GET", Path: "/api/vault/enclave", Query: "release=" + strings.Repeat("cd", 48),
		VaultID: ACAppVaultID, KID: akid, TS: t0.Unix(), Nonce: nonce})
	if err != nil {
		return nil, err
	}
	sample := []byte{248, 255, 0, 30, 31, 247, 1, 2, 3, 4, 5}
	code, used, err := altchan.CodeFromBytes(sample)
	if err != nil {
		return nil, err
	}
	kc := rep(SeedKCode, 32)
	mac := func(parts ...string) string {
		m := hmac.New(sha256.New, kc)
		for i, p := range parts {
			if i > 0 {
				m.Write([]byte{0})
			}
			m.Write([]byte(p))
		}
		return hx(m.Sum(nil))
	}
	eqr := (&altchan.EnrollQR{API: "https://account.vettid.org", Secret: secret}).Marshal()
	rqr := altchan.RecoveryQR(&altchan.RecoveryCode{API: "https://account.vettid.org", VaultID: ACVaultID, RecoveryID: RecRecoveryID,
		Code: "50M2GA1850M2GA1850M2GA1850M2GA18"})
	return obj{
		{"description", "VAULT-MESSAGING 0.15.0 §11.12 (ENROLLMENT-CODES.md; MEMBER-API 2.0.0): not printed in §16; generated by vettid-vault for the member API and the apps to reproduce. The app key is TEST ONLY. akid = hex(SHA-256(SPKI DER)[0:16]). X-VettID-App: v=1; vault=<vault_id or empty>; kid=<akid>; ts=<Unix s>; nonce=<b64url 16 B>; sig=<b64url DER ECDSA>, sig = ECDSA P-256 / SHA-256 over signing_string (here with RFC 6979 nonces; any valid signature verifies). The typed code: bytes >= 248 discarded, the rest mod 31 into code_alphabet. qr_lookup = HMAC-SHA-256(k_code, \"qr\" || 0x00 || secret); code_mac = HMAC-SHA-256(k_code, \"code\" || 0x00 || user_guid || 0x00 || code). The enrollment QR and the recovery QR (with api) are compact JSON."},
		{"app_key_scalar_hex", hx(rep(SeedAppKey, 32))},
		{"app_key_spki_b64", b64(der)},
		{"akid", akid},
		{"label", altchan.LabelAppRequest},
		{"unlock_request", unlock},
		{"redeem_request", redeem},
		{"enclave_request", enclave},
		{"code_alphabet", altchan.CodeAlphabet},
		{"code_random_hex", hx(sample)},
		{"code_bytes_used", used},
		{"code", code},
		{"code_display", altchan.FormatCode(code)},
		{"k_code_hex", hx(kc)},
		{"user_guid", "user-0001"},
		{"qr_secret", qs},
		{"qr_lookup_hex", mac("qr", qs)},
		{"code_mac_hex", mac("code", "user-0001", code)},
		{"enroll_qr", string(eqr)},
		{"enroll_app_link", "https://account.vettid.org/vault/enroll/#s=" + qs},
		{"recovery_qr", string(rqr)},
		{"email", "member@example.com"},
		{"email_hint", altchan.EmailHint("member@example.com")},
	}, nil
}
