// Package pins holds the vendor trust anchors that release images and the
// reference client pin (VAULT-MESSAGING §11.2, §11.7; VAULT-PLAN D5):
//
//   - the AWS Nitro Enclaves root (attestation documents, §11.2);
//   - Google's hardware key attestation roots (Android, §11.7);
//   - Apple's App Attestation root (iOS, §11.7).
//
// Each certificate is the vendor's published file, checked by SHA-256
// fingerprint in the tests. Changing any of them is a release (§11.10).
// Test roots never live here: they are generated by internal/enclavetest,
// which release builds cannot link (make check-tcb).
package pins

import (
	"crypto/x509"
	"embed"
	"encoding/pem"
	"sync"
)

//go:embed roots/*.pem
var rootFS embed.FS

// Source URLs, for re-verification:
//
//	AWS:    https://aws-nitro-enclaves.amazonaws.com/AWS_NitroEnclaves_Root-G1.zip
//	Google: https://developer.android.com/privacy-and-security/security-key-attestation#root_certificate
//	Apple:  https://www.apple.com/certificateauthority/Apple_App_Attestation_Root_CA.pem
const (
	fileNitro = "roots/aws-nitro-enclaves-root-g1.pem"
	fileApple = "roots/apple-app-attestation-root-ca.pem"
)

// Google's hardware attestation roots. The three RSA certificates carry the
// same key (re-issued with later expiry); the 2016 issue of that key expired
// in May 2026 and is not pinned. "Key Attestation CA1" is the EC P-384 root
// introduced in 2025.
var fileGoogle = []string{
	"roots/google-hw-attestation-rsa-2019.pem",
	"roots/google-hw-attestation-rsa-2021.pem",
	"roots/google-hw-attestation-rsa-2022.pem",
	"roots/google-key-attestation-ca1-ec-2025.pem",
}

func load(name string) *x509.Certificate {
	b, err := rootFS.ReadFile(name)
	if err != nil {
		panic("pins: missing " + name)
	}
	blk, _ := pem.Decode(b)
	if blk == nil || blk.Type != "CERTIFICATE" {
		panic("pins: bad PEM " + name)
	}
	c, err := x509.ParseCertificate(blk.Bytes)
	if err != nil {
		panic("pins: bad certificate " + name)
	}
	return c
}

var (
	once         sync.Once
	nitro, apple *x509.Certificate
	google       []*x509.Certificate
)

func initAll() {
	nitro = load(fileNitro)
	apple = load(fileApple)
	for _, f := range fileGoogle {
		google = append(google, load(f))
	}
}

// NitroRoot returns the AWS Nitro Enclaves root certificate.
func NitroRoot() *x509.Certificate { once.Do(initAll); return nitro }

// AppleAppAttestRoot returns Apple's App Attestation root certificate.
func AppleAppAttestRoot() *x509.Certificate { once.Do(initAll); return apple }

// GoogleAttestationRoots returns Google's hardware attestation roots.
func GoogleAttestationRoots() []*x509.Certificate {
	once.Do(initAll)
	return append([]*x509.Certificate(nil), google...)
}
